plugins:
  - uses:
    - plugin: https://ubiquibot-command-wallet.fernand-veyrier.workers.dev
  - uses:
    - plugin: https://ubiquibot-command-query-user.fernand-veyrier.workers.dev
      with:
        allowPublicQuery: false
  - uses:
    - plugin: https://ubiquibot-assistive-pricing.fernand-veyrier.workers.dev
      with:
        labels:
          time:
            - "Time: <1 Hour"
            - "Time: <2 Hours"
            - "Time: <4 Hours"
            - "Time: <1 Day"
            - "Time: <1 Week"
          priority:
            - "Priority: 1 (Normal)"
            - "Priority: 2 (Medium)"
            - "Priority: 3 (High)"
            - "Priority: 4 (Urgent)"
            - "Priority: 5 (Emergency)"
        basePriceMultiplier: 1
        publicAccessControl:
          setLabel: true
          fundExternalClosedIssue: false
  - uses:
    - plugin: gentlementlegen/conversation-rewards@feat/symbol-coefficient
  - uses:
    - plugin: Meniole/conversation-rewards
      with:
        evmNetworkId: 100
        evmPrivateEncrypted: "kmpTKq5Wh9r9x5j3U9GqZr3NYnjK2g0HtbzeUBOuLC2y3x8ja_SKBNlB2AZ6LigXHP_HeMitftVUtzmoj8CFfVP9SqjWoL6IPku1hVTWkdTn97g1IxzmjydFxjdcf0wuDW1hvVtoq3Uw5yALABqxcQ"
        incentives:
          contentEvaluator: {}
          userExtractor:
            redeemTask: true
          dataPurge: {}
          formattingEvaluator:
            multipliers:
              - select: [ ISSUE_SPECIFICATION ]
                formattingMultiplier: 1
                symbols:
                  "\\b\\w+\\b": 0.1
                  "\\b\\W+\\b": 0.1
                scores:
                  br: 0
                  code: 1
                  p: 1
                  em: 0
                  img: 0
                  strong: 0
                  blockquote: 0
                  h1: 1
                  h2: 1
                  h3: 1
                  h4: 1
                  h5: 1
                  h6: 1
                  a: 1
                  li: 1
                  td: 1
                  hr: 0
              - select: [ ISSUE_AUTHOR ]
                formattingMultiplier: 1
                symbols:
                  "\\b\\w+\\b": 0.2
              - select: [ ISSUE_ASSIGNEE ]
                formattingMultiplier: 0
                symbols:
                  "\\b\\w+\\b": 0
              - select: [ ISSUE_COLLABORATOR ]
                formattingMultiplier: 1
                symbols:
                  "\\b\\w+\\b": 0.1
              - select: [ ISSUE_CONTRIBUTOR ]
                formattingMultiplier: 0.25
                symbols:
                  "\\b\\w+\\b": 0.1
              - select: [ PULL_SPECIFICATION ]
                formattingMultiplier: 0
                symbols:
                  "\\b\\w+\\b": 0
              - select: [ PULL_AUTHOR ]
                formattingMultiplier: 2
                symbols:
                  "\\b\\w+\\b": 0.2
              - select: [ PULL_ASSIGNEE ]
                formattingMultiplier: 1
                symbols:
                  "\\b\\w+\\b": 0.1
              - select: [ PULL_COLLABORATOR ]
                formattingMultiplier: 1
                symbols:
                  "\\b\\w+\\b": 0.1
              - select: [ PULL_CONTRIBUTOR ]
                formattingMultiplier: 0.25
                symbols:
                  "\\b\\w+\\b": 0.1
            permitGeneration: {}
            githubComment:
              post: true
              debug: true
  - uses:
    - plugin: Meniole/user-activity-watcher
      with:
        unassignUserThreshold: "5 minutes"
        sendRemindersThreshold: "1 minutes"
  - uses:
    - plugin: Meniole/automated-merging:compute.yml@test
      runsOn: ["issues.labeled"]
      with:
        approvalsRequired:
          collaborator: 1
        mergeTimeout:
          collaborator: "2 minutes"
        repos:
          monitor: [ "Meniole/automated-merging" ]
  # - uses:
  #   - plugin: Meniole/test-automated-merging@main
  #     with:
  #       approvalsRequired:
  #         collaborator: 1
  #       mergeTimeout:
  #         collaborator: "2 minutes"
  - uses:
    - plugin: https://ubiquibot-command-start-stop.fernand-veyrier.workers.dev
      with:
        isEnabled: true
        timers:
          reviewDelayTolerance: 86000
          taskStaleTimeoutDuration: 2580000
        miscellaneous:
          # maxConcurrentTasks: []
          # maxConcurrentTasks: 0
          startRequiresWallet: true
  # - uses:
  #   - plugin: http://127.0.0.1:9090
  #     runsOn: [ "issue_comment.created" ]
  #     with:
  #       response: world
