# etcf
plugins:
  - test: "invalid 1"
    uses:
      - plugin: "test"
  - uses:
    - plugin: https://ubiquibot-command-wallet-development.fernand-veyrier.workers.dev
  - uses:
    - plugin: https://ubiquibot-command-query-user-development.fernand-veyrier.workers.dev
      with:
        allowPublicQuery: false
  - uses:
    - plugin: https://ubiquibot-assistive-pricing-development.fernand-veyrier.workers.dev
      with:
        labels:
          time:
            - "Time: <1 Hour"
            - "Time: <2 Hours"
            - "Time: <4 Hours"
            - "Time: <1 Day"
            - "Time: <1 Week"
          priority:
            - "Priority: 1 (Normal)"
            - "Priority: 2 (Medium)"
            - "Priority: 3 (High)"
            - "Priority: 4 (Urgent)"
            - "Priority: 5 (Emergency)"
        basePriceMultiplier: 1
        publicAccessControl:
          setLabel: true
          fundExternalClosedIssue: false
  - skipBotEvents: false
    uses:
    - plugin: Meniole/conversation-rewards@feat/element-score
      with:
        logLevel: "debug"
        evmNetworkId: 100
        evmPrivateEncrypted: "kmpTKq5Wh9r9x5j3U9GqZr3NYnjK2g0HtbzeUBOuLC2y3x8ja_SKBNlB2AZ6LigXHP_HeMitftVUtzmoj8CFfVP9SqjWoL6IPku1hVTWkdTn97g1IxzmjydFxjdcf0wuDW1hvVtoq3Uw5yALABqxcQ"
        incentives:
          contentEvaluator:
            openAi:
              model: "llama3-groq-70b-8192-tool-use-preview"
              endpoint: "https://api.groq.com/openai/v1"
          userExtractor:
            redeemTask: true
          dataPurge: {}
          formattingEvaluator:
            multipliers:
              - role: [ ISSUE_SPECIFICATION ]
                multiplier: 1
                rewards:
                  regex:
                    "\\b\\w+\\b": 0.1
                    "\\b\\W+\\b": 0.1
                  html:
                    br: 0
                    code: 3
                    p: 1
                    em: 0
                    img: 2
                    strong: 0
                    blockquote: 0
                    h1: 1
                    h2: 1
                    h3: 1
                    h4: 1
                    h5: 1
                    h6: 1
                    a: 1
                    li: 1
                    td: 1
                    hr: 0
                    ol: 0
              - role: [ ISSUE_AUTHOR ]
                multiplier: 1
                rewards:
                  regex:
                    "\\b\\w+\\b": 0.2
              - role: [ ISSUE_ASSIGNEE ]
                multiplier: 0
                rewards:
                  regex:
                    "\\b\\w+\\b": 0
              - role: [ ISSUE_COLLABORATOR ]
                multiplier: 1
                rewards:
                  regex:
                    "\\b\\w+\\b": 0.1
              - role: [ ISSUE_CONTRIBUTOR ]
                multiplier: 0.25
                rewards:
                  regex:
                    "\\b\\w+\\b": 0.1
              - role: [ PULL_SPECIFICATION ]
                multiplier: 0
                rewards:
                  regex:
                    "\\b\\w+\\b": 0
              - role: [ PULL_AUTHOR ]
                multiplier: 2
                rewards:
                  regex:
                    "\\b\\w+\\b": 0.2
              - role: [ PULL_ASSIGNEE ]
                multiplier: 1
                rewards:
                  regex:
                    "\\b\\w+\\b": 0.1
              - role: [ PULL_COLLABORATOR ]
                multiplier: 1
                rewards:
                  regex:
                    "\\b\\w+\\b": 0.1
              - role: [ PULL_CONTRIBUTOR ]
                multiplier: 0.25
                rewards:
                  regex:
                    "\\b\\w+\\b": 0.1
          permitGeneration: {}
          githubComment:
            post: true
            debug: true
  - uses:
    - plugin: Meniole/user-activity-watcher@fork/ubq-testing/fix-issues
    # - plugin: Meniole/user-activity-watcher@main
      runsOn: ["issues.labeled"]
      with:
        disqualification: "2 minutes"
        warning: "1 minute"
        watch:
          optOut: 
            - "repoName"
            - "repoName2"
  - uses:
    - plugin: Meniole/automated-merging@fork/ubq-testing/development
      # runsOn: ["issues.labeled", "issues.unlabeled"]
      with:
        approvalsRequired:
          collaborator: 1
        mergeTimeout:
          collaborator: "2 minutes"
        repos:
          monitor: [ ]
          ignore: ["conversation-rewards"]
        allowedReviewerRoles: ["OWNER", "COLLABORATOR"]
  - uses:
    # - plugin: Meniole/issue-comment-embeddings@fork/sshivaditya2019/development
    - plugin: https://ubiquibot-issue-comment-embeddings-main.fernand-veyrier.workers.dev
  - uses:
    # - plugin: https://ubiquibot-command-start-stop-development.fernand-veyrier.workers.dev
    - plugin: https://ubiquibot-command-start-stop-chore-new-assign-design.fernand-veyrier.workers.dev
      with:
        reviewDelayTolerance: "3 Days"
        taskStaleTimeoutDuration: "1 minute"
        maxConcurrentTasks:
          member: 1
        #   admin: 1
        #   contributor: 1
        startRequiresWallet: true # default is true
  - uses:
    - plugin: https://comic-bee-miserably.ngrok-free.app
      # runsOn: [ "issue_comment.created" ]
      with:
        reviewDelayTolerance: "3 Days"
        taskStaleTimeoutDuration: "30 Days"
