plugins:
  - uses:
    - plugin: https://ubiquibot-command-wallet.fernand-veyrier.workers.dev
  - uses:
    - plugin: https://ubiquibot-command-query-user.fernand-veyrier.workers.dev
      with:
        allowPublicQuery: false
  - uses:
    - plugin: https://ubiquibot-assistive-pricing.fernand-veyrier.workers.dev
      with:
        labels:
          time:
            - "Time: <1 Hour"
            - "Time: <2 Hours"
            - "Time: <4 Hours"
            - "Time: <1 Day"
            - "Time: <1 Week"
          priority:
            - "Priority: 1 (Normal)"
            - "Priority: 2 (Medium)"
            - "Priority: 3 (High)"
            - "Priority: 4 (Urgent)"
            - "Priority: 5 (Emergency)"
        basePriceMultiplier: 1
        publicAccessControl:
          setLabel: true
          fundExternalClosedIssue: false
  # - uses:
    # - plugin: gentlementlegen/conversation-rewards@fix/waiting-message
  - uses:
      - plugin: Meniole/conversation-rewards@feat/graphql-pr-fetch
    # - plugin: Meniole/conversation-rewards@main
      with:
        evmNetworkId: 100
        evmPrivateEncrypted: "kmpTKq5Wh9r9x5j3U9GqZr3NYnjK2g0HtbzeUBOuLC2y3x8ja_SKBNlB2AZ6LigXHP_HeMitftVUtzmoj8CFfVP9SqjWoL6IPku1hVTWkdTn97g1IxzmjydFxjdcf0wuDW1hvVtoq3Uw5yALABqxcQ"
        incentives:
          contentEvaluator: {}
          userExtractor:
            redeemTask: true
          dataPurge: {}
          formattingEvaluator:
            multipliers:
              - select: [ ISSUE_SPECIFICATION ]
                multiplier: 1
                rewards:
                  regex:
                    "\\b\\w+\\b": 0.1
                    "\\b\\W+\\b": 0.1
                  html:
                    br: 0
                    code: 1
                    p: 1
                    em: 0
                    img: 0
                    strong: 0
                    blockquote: 0
                    h1: 1
                    h2: 1
                    h3: 1
                    h4: 1
                    h5: 1
                    h6: 1
                    a: 1
                    li: 1
                    td: 1
                    hr: 0
              - select: [ ISSUE_AUTHOR ]
                multiplier: 1
                rewards:
                  regex:
                    "\\b\\w+\\b": 0.2
              - select: [ ISSUE_ASSIGNEE ]
                multiplier: 0
                rewards:
                  regex:
                    "\\b\\w+\\b": 0
              - select: [ ISSUE_COLLABORATOR ]
                multiplier: 1
                rewards:
                  regex:
                    "\\b\\w+\\b": 0.1
              - select: [ ISSUE_CONTRIBUTOR ]
                multiplier: 0.25
                rewards:
                  regex:
                    "\\b\\w+\\b": 0.1
              - select: [ PULL_SPECIFICATION ]
                multiplier: 0
                rewards:
                  regex:
                    "\\b\\w+\\b": 0
              - select: [ PULL_AUTHOR ]
                multiplier: 2
                rewards:
                  regex:
                  "\\b\\w+\\b": 0.2
              - select: [ PULL_ASSIGNEE ]
                multiplier: 1
                rewards:
                  regex:
                    "\\b\\w+\\b": 0.1
              - select: [ PULL_COLLABORATOR ]
                multiplier: 1
                rewards:
                  regex:
                    "\\b\\w+\\b": 0.1
              - select: [ PULL_CONTRIBUTOR ]
                multiplier: 0.25
                rewards:
                  regex:
                    "\\b\\w+\\b": 0.1
            permitGeneration: {}
            githubComment:
              post: true
              debug: true
  - uses:
    - plugin: Meniole/user-activity-watcher@main
    # - plugin: Meniole/user-activity-watcher@main
      runsOn: ["issues.labeled"]
      with:
        disqualification: "2 minutes"
        warning: "1 minute"
        watch:
          optOut: 
            - "repoName"
            - "repoName2"
  - uses:
    - plugin: Meniole/automated-merging:compute.yml@main
      # runsOn: ["issues.labeled"]
      with:
        approvalsRequired:
          collaborator: 1
        mergeTimeout:
          collaborator: "2 minutes"
        repos:
          monitor: [ ]
          ignore: ["conversation-rewards"]
  - uses:
    - plugin: https://ubiquibot-command-start-stop.fernand-veyrier.workers.dev
      with:
        timers:
          reviewDelayTolerance: 86000
          taskStaleTimeoutDuration: 2580000
        miscellaneous:
          maxConcurrentTasks:
            - role: Admin
              limit: 20
          # maxConcurrentTasks: 3
          startRequiresWallet: true
  # - uses:
  #   - plugin: http://127.0.0.1:9090
  #     runsOn: [ "issue_comment.created" ]
  #     with:
  #       response: world
