# ee
plugins:
  - uses:
    - plugin: https://comic-bee-miserably.ngrok-free.app
      # runsOn: [ "issue_comment.created" ] 
      with:
        reviewDelayTolerance: "1 day"
        taskStaleTimeoutDuration: "27 Days"
        startRequiresWallet: true
      # with:
      #   registerWalletWithVerification: "maybe"
        # reviewDelayTolerance: "3 Days"
        # taskStaleTimeoutDuration: "30 Days"
        # startRequiresWallet: true
        # maxConcurrentTasks:
        #   admin: 100
        #   member: 20
        #   contributor: 5
  - uses:
    - plugin: Meniole/automated-merging@feat/schema-validation
      with:
        approvalsRequired:
          collaborator: "10"
        mergeTimeout:
          collaborator: "2 minutes"
        repos:
          monitor: [ ]
          ignore: ["conversation-rewards"]
        allowedReviewerRoles: ["OWNER", "COLLABORATOR", true]
  # # - uses:
  # #   - some-stuff: {}
  # # - test: "invalid 1"
  # #   uses:
  # #     - plugin: "test"
  - uses:
    - plugin: https://ubiquibot-command-wallet-feat-schema-validation.fernand-veyrier.workers.dev
      with:
        registerWalletWithVerification: "maybe"
  - uses:
    - plugin: https://ubiquibot-command-query-user-feat-schema-validation.fernand-veyrier.workers.dev
      with:
        allowPublicQuery: "no"
  - uses:
    - plugin: https://ubiquibot-assistive-pricing-fork-ubq-testing-development.fernand-veyrier.workers.dev
      with:
        labels:
          time:
            - "Time: <1.5 Minutes"
            - "Time: <1 Hour"
            - "Time: <2 Hours"
            - "Time: <4 Hours"
            - "Time: <1 Day"
            - "Time: <1 Week"
          priority:
            - "Priority: 1 (Normal)"
            - "Priority: 2 (Medium)"
            - "Priority: 3 (High)"
            - "Priority: 4 (Urgent)"
            - "Priority: 5 (Emergency)"
        basePriceMultiplier: 2
        publicAccessControl:
          setLabel: true
          fundExternalClosedIssue: false
  # - skipBotEvents: false
  - uses:
    - plugin: Meniole/conversation-rewards@feat/multiple-prs
      with:
        logLevel: "debug"
        evmNetworkId: 100
        evmPrivateEncrypted: "kmpTKq5Wh9r9x5j3U9GqZr3NYnjK2g0HtbzeUBOuLC2y3x8ja_SKBNlB2AZ6LigXHP_HeMitftVUtzmoj8CFfVP9SqjWoL6IPku1hVTWkdTn97g1IxzmjydFxjdcf0wuDW1hvVtoq3Uw5yALABqxcQ:159901852"
        incentives:
          contentEvaluator:
            openAi:
              model: "llama3-groq-70b-8192-tool-use-preview"
              endpoint: "https://api.groq.com/openai/v1"
          userExtractor:
            redeemTask: true
          dataPurge: {}
          formattingEvaluator:
            multipliers:
              - role: [ ISSUE_SPECIFICATION ]
                multiplier: 3
                rewards:
                  wordValue: 0.1
                  # html:
                  #   br: 0
                  #   code: 5
                  #   p: 1
                  #   em: 0
                  #   img: 5
                  #   strong: 0
                  #   blockquote: 0
                  #   h1: 1
                  #   h2: 1
                  #   h3: 1
                  #   h4: 1
                  #   h5: 1
                  #   h6: 1
                  #   a: 5
                  #   li: 1
                  #   td: 1
                  #   hr: 0
              - role: [ ISSUE_AUTHOR ]
                multiplier: 1
                rewards:
                  wordValue: 0.2
              - role: [ ISSUE_ASSIGNEE ]
                multiplier: 1
                rewards:
                  wordValue: 0.1
              - role: [ ISSUE_COLLABORATOR ]
                multiplier: 1
                rewards:
                  wordValue: 0.1
              - role: [ ISSUE_CONTRIBUTOR ]
                multiplier: 0.25
                rewards:
                  wordValue: 0.1
              - role: [ PULL_SPECIFICATION ]
                multiplier: 0
                rewards:
                  wordValue: 0
              - role: [ PULL_AUTHOR ]
                multiplier: 0
                rewards:
                  wordValue: 0.2
              - role: [ PULL_ASSIGNEE ]
                multiplier: 1
                rewards:
                  wordValue: 0.1
              - role: [ PULL_COLLABORATOR ]
                multiplier: 1
                rewards:
                  wordValue: 0.1
              - role: [ PULL_CONTRIBUTOR ]
                multiplier: 0.25
                rewards:
                  wordValue: 0.1
          # permitGeneration:
          #   enabled: true
          # githubComment:
          #   post: true
          #   debug: false
          # permitGeneration:
          #   enabled: true
          # githubComment:
          #   post: true
          #   debug: false
          permitGeneration: {}
          githubComment:
            post: true
            debug: true
  - uses:
    - plugin: Meniole/user-activity-watcher@feat/schema-validation
    # - plugin: Meniole/user-activity-watcher@main
      runsOn: ["issues.labeled"]
      with:
        disqualification: "2 minutes"
        warning: "1 minute"
        watch:
          optOut:
            - {}
            - "repoName"
            - "repoName2"
  # - uses:
  #   # - plugin: Meniole/issue-comment-embeddings@fork/sshivaditya2019/development
  #   - plugin: https://ubiquibot-issue-comment-embeddings-main.fernand-veyrier.workers.dev
  - uses:
    - plugin: https://ubiquibot-command-start-stop-schema-validation.fernand-veyrier.workers.dev
    # - plugin: https://ubiquibot-command-start-stop-fork-ubq-testing-fix-approved-role.fernand-veyrier.workers.dev
      with:
        reviewDelayTolerance: "3 Days"
        taskStaleTimeoutDuration: "1 minute"
        maxConcurrentTasks:
          member: true
        #   admin: 1
        #   contributor: 1
        startRequiresWallet: true # default is true
        rolesWithReviewAuthority:
          - "OWNER"
          - "MEMBER"
